# Generated by Django 4.1 on 2023-09-13 20:42

from django.db import migrations, models
import main.models.response


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="request",
            field=models.JSONField(default=main.models.response.default_json),
        ),
    ]
