# Generated by Django 4.1 on 2023-09-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_response_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(default="", max_length=100)),
                ("url", models.CharField(default="", max_length=100)),
                ("agent", models.CharField(default="", max_length=100)),
                ("ip", models.CharField(default="", max_length=100)),
                ("method", models.CharField(default="", max_length=100)),
                ("status_code", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
