# Generated by Django 5.0.6 on 2024-06-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='toxicity',
        ),
    ]
