# Generated by Django 5.0.6 on 2024-07-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_response_toxicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="agent",
            field=models.CharField(default="", max_length=255),
        ),
    ]
