# Generated by Django 5.0.6 on 2024-07-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_log_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.project",
            ),
        ),
    ]
