# Generated by Django 5.0.6 on 2024-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_response_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="mode",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="response",
            name="model",
            field=models.CharField(default="", max_length=100),
        ),
    ]
